### ISSUE TITLE
Default for sonar.branch is trunk

### ISSUE THREAD

**Issue by Loki-Afro** [IntershopCommunicationsAG/sonarqube-gradle-plugin#7]
Default for sonar.branch is `trunk` which is kind of unnecessary. 

**tl;dr**
`trunk` is just a very nasty default

http://docs.sonarqube.org/display/SONAR/Analysis+Parameters

It should not add `sonar.branch` at all if it is not specified.

As from the documentation above `Two branches of the same project are considered to be different projects`

Background: You do not always have on a CI Environment the current branch name, see http://stackoverflow.com/questions/20541609/how-to-receive-local-git-branch-name-with-jenkins-git-plugin

And who on earth uses svn, really? ;)

**Comment by m-raab** [comment]
Yes. that's correct. 'trunk' is a bad idea for the default value. This issue is solved in version 2.1 and the documentation was adapted. But if you use stabilization branches it makes sense to have different 'projects' in sonarqube for different branches.

A lot of projects are using Subversion, but that's correct, Git is better.
